name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-php@v4
      with:
        php-version: '8.2'
    - name: Run PHPUnit tests
      run: |
        composer install
        chmod +x ./tests.sh
        ./tests.sh
      shell: bash